version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./vuln_info_bot:/app/vuln_info_bot
